export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const FETCH_MESSAGES_INIT_STATE = "FETCH_MESSAGES_INIT_STATE";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILED = "FETCH_MESSAGES_FAILED";

export const SET_SKIP_FETCH_MESSAGES = "SET_SKIP_FETCH_MESSAGES";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_INIT_STATE = "SEND_MESSAGE_INIT_STATE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED";

export const RECEIVE_MESSAGE_CHUNK = "RECEIVE_MESSAGE_CHUNK_MESSAGE";
export const RECEIVE_MESSAGE_CHUNK_FAILED = "RECEIVE_MESSAGE_CHUNK_FAILED";
    
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_MESSAGE_INIT_STATE = "DELETE_MESSAGE_INIT_STATE";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAILED = "DELETE_MESSAGE_FAILED";