export const AGENT_INIT = "AGENT_INIT";
export const SHOW_NEW_AGENT_CHAT = "SHOW_NEW_AGENT_CHAT";

export const SET_ACTIVE_AGENT = "SET_ACTIVE_AGENT";
export const SET_ACTIVE_AGENT_INIT_STATE = "SET_ACTIVE_AGENT_INIT_STATE";
export const SET_ACTIVE_AGENT_SUCCESS = "SET_ACTIVE_AGENT_SUCCESS";
export const SET_ACTIVE_AGENT_FAILED = "SET_ACTIVE_AGENT_FAILED";

export const GET_AI_AGENTS = "GET_AI_AGENTS";
export const GET_AI_AGENTS_INIT_STATE = "GET_AI_AGENTS_INIT_STATE";
export const GET_AI_AGENTS_SUCCESS = "GET_AI_AGENTS_SUCCESS";
export const GET_AI_AGENTS_FAILED = "GET_AI_AGENTS_FAILED";

export const GET_USER_AGENTS = "GET_USER_AGENTS";
export const GET_USER_AGENTS_INIT_STATE = "GET_USER_AGENTS_INIT_STATE";
export const GET_USER_AGENTS_SUCCESS = "GET_USER_AGENTS_SUCCESS";
export const GET_USER_AGENTS_FAILED = "GET_USER_AGENTS_FAILED";

export const UPDATE_AGENT_DATA = "UPDATE_AGENT_DATA";
export const UPDATE_AGENT_DATA_INIT_STATE = "UPDATE_AGENT_DATA_INIT_STATE"; 
export const UPDATE_AGENT_DATA_SUCCESS = "UPDATE_AGENT_DATA_SUCCESS";
export const UPDATE_AGENT_DATA_FAILED = "UPDATE_AGENT_DATA_FAILED";

export const UPDATE_AGENT_AVATAR = "UPDATE_AGENT_AVATAR";
export const UPDATE_AGENT_AVATAR_INIT_STATE = "UPDATE_AGENT_AVATAR_INIT_STATE";
export const UPDATE_AGENT_AVATAR_SUCCESS = "UPDATE_AGENT_AVATAR_SUCCESS";
export const UPDATE_AGENT_AVATAR_FAILED = "UPDATE_AGENT_AVATAR_FAILED";