export const AGENT_INIT = "AGENT_INIT";
export const GET_AGENT = "GET_AGENT";
export const GET_AGENT_SUCCESS = "GET_AGENT_SUCCESS";
export const GET_AGENT_FAILED = "GET_AGENT_FAILED";

export const UPDATE_AGENT_DATA = "UPDATE_AGENT_DATA";
export const UPDATE_AGENT_DATA_SUCCESS = "UPDATE_AGENT_DATA_SUCCESS";
export const HIDE_AGENT_DATA_SUCCESS_MESSAGE = "HIDE_AGENT_DATA_SUCCESS_MESSAGE";
export const UPDATE_AGENT_DATA_FAILED = "UPDATE_AGENT_DATA_FAILED";

export const UPDATE_AGENT_AVATAR = "UPDATE_AGENT_AVATAR";
export const UPDATE_AGENT_AVATAR_SUCCESS = "UPDATE_AGENT_AVATAR_SUCCESS";
export const HIDE_AGENT_AVATAR_SUCCESS_MESSAGE = "HIDE_AGENT_AVATAR_SUCCESS_MESSAGE";
export const UPDATE_AGENT_AVATAR_FAILED = "UPDATE_AGENT_AVATAR_FAILED";