# Generated by Django 4.2.1 on 2024-02-22 09:33

import ai_agent_profile_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to=ai_agent_profile_app.models.get_image_filename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agent_app.agent')),
            ],
        ),
    ]
