# Generated by Django 4.2.1 on 2024-01-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent_profile_app', '0002_alter_aiagentprofile_ai_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagentprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
