FROM node:18.17.1-alpine AS builder

# Set working directory
WORKDIR /frontend

# Create a group and user for the build stage
RUN addgroup -S appuser && adduser -S -G appuser appuser

# Change ownership of the app directory
RUN chown -R appuser:appuser /frontend

# Copy package files and install dependencies
COPY --chown=appuser:appgroup . .

USER appuser

RUN yarn install

EXPOSE 3000

# Start the development server
CMD ["yarn", "start"]