FROM node:18.17.1-alpine AS builder

# Set working directory
WORKDIR /frontend

# Create a group and user for the build stage
RUN addgroup -S fosterflow && adduser -S -G fosterflow fosterflow

# Change ownership of the app directory
RUN chown -R fosterflow:fosterflow /frontend

# Copy package files and install dependencies
COPY --chown=fosterflow:fosterflow . .

USER fosterflow

RUN yarn install

EXPOSE 3000

# Start the development server
CMD ["yarn", "start"]