FROM node:18.17.1-alpine AS builder

# Set working directory
WORKDIR /frontend

# Create a group and user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Change ownership of the directory
RUN chown -R appuser:appgroup /frontend

# Copy package files and install dependencies
COPY --chown=appuser:appgroup . .

USER appuser

RUN yarn install

EXPOSE 3000

# Start the development server
CMD ["yarn", "start"]