FROM node:18.17.1-alpine

# Bundle static assets with nginx
FROM nginx:1.21.0-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /frontend

COPY . .

RUN yarn install
RUN yarn build 

ENV NODE_ENV production
# Copy built assets from builder
COPY /frontend/build /usr/share/nginx/html

EXPOSE 3000

# Start nginx
CMD ["nginx", "-g", "daemon off;"]