# Generated by Django 4.2.1 on 2024-02-29 20:38

from django.db import migrations, models
import django.db.models.deletion
import user_agent_profile_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to=user_agent_profile_app.models.get_image_filename)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agent_app.agent')),
            ],
        ),
    ]
