version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:15.4-alpine
    privileged: true
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - myNetwork
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
    networks:
      - myNetwork
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    container_name: backend
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env
    networks:
      - myNetwork
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/backend
    entrypoint: sh ./django-entrypoint-prod.sh
    restart: always  
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery:
    container_name: celery
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    command: celery -A project worker --loglevel=info
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always 
    networks:
      - myNetwork

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
        REACT_APP_WS_URL: ${REACT_APP_WS_URL}
        REACT_APP_SUPPORT_EMAIL: ${REACT_APP_SUPPORT_EMAIL}
        REACT_APP_BASE_MODEL_AGENT_ID: ${REACT_APP_BASE_MODEL_AGENT_ID}
    ports:
      - "80:80"   # For HTTP traffic
      - "443:443" # For HTTPS traffic
    expose:
      - "80"
      - "443"
    volumes:
      - ./frontend:/frontend
      - '/frontend/node_modules'
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - myNetwork
    env_file:
      - .env
    depends_on:
      - db
      - backend
    restart: always 
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis:
    driver: local

networks:
  myNetwork:
    driver: bridge