# API Exposure Overlay for Docker Compose
# This overlay file exposes the Ollama API to external services by:
# - Configuring port mapping for the Ollama service (default port 11434)
# - Making the API accessible outside the container stack
# 
# Use with: docker compose -f docker-compose.yaml -f docker-compose.api.yaml up

services:
  ollama:
    # Expose Ollama API outside the container stack
    ports:
      - ${OLLAMA_WEBAPI_PORT-11434}:11434
