version: '3.1'
services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    networks:
      - myNetwork
  
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8080:8080
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db
    networks:
      - myNetwork
  
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: bash -c "yarn start"
    networks:
      - myNetwork
    depends_on:
      - db
      - backend


networks:
  myNetwork:
    driver: bridge