version: '3.1'
services:
  db:
    container_name: postgres
    image: postgres:15.4-alpine
    privileged: true
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - myNetwork
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
    networks:
      - myNetwork
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
    entrypoint: sh ./django-entrypoint.sh
    environment:
      - REDIS_HOST=redis
    restart: always
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - myNetwork
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  celery:
    container_name: celery
    build: ./backend
    command: celery -A project worker --loglevel=info
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - myNetwork

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./frontend:/frontend
      - '/frontend/node_modules'
    networks:
      - myNetwork
    env_file:
      - .env
    depends_on:
      - db
      - backend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  swagger:
    container_name: swagger
    build: ./swagger
    ports:
      - "8080:8080"
    volumes:
      - ./swagger:/swagger
    command: bash -c "npm install && npm start"
    networks:
      - myNetwork
    depends_on:
      - db
      - backend

volumes:
  redis:
    driver: local

networks:
  myNetwork:
    driver: bridge
