# Custom Data Directory Overlay for Docker Compose
# This overlay file configures custom data directory mapping for the Ollama service by:
# - Mapping a host directory (default: ./ollama-data) to the Ollama data directory inside the container
# - Allowing customization of the host directory path via the OLLAMA_DATA_DIR environment variable
#
# Use with: docker compose -f docker-compose.yaml -f docker-compose.data.yaml up

services:
  ollama:
    volumes:
      - ${OLLAMA_DATA_DIR-./ollama-data}:/root/.ollama
