# Playwright Support Overlay for Docker Compose
# This overlay file adds Playwright support for web automation and testing by:
# - Creating a Playwright service using Microsoft's Playwright Docker image
# - Running a Playwright server on port 3000
# - Configuring the open-webui service to use Playwright as the RAG web loader engine
# - Setting up WebSocket communication between the services
#
# Use with: docker compose -f docker-compose.yaml -f docker-compose.playwright.yaml up

services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.49.1-noble # Version must match requirements.txt
    container_name: playwright
    command: npx -y playwright@1.49.1 run-server --port 3000 --host 0.0.0.0

  open-webui:
    environment:
      - 'RAG_WEB_LOADER_ENGINE=playwright'
      - 'PLAYWRIGHT_WS_URI=ws://playwright:3000'