services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.49.1-noble # Version must match requirements.txt
    container_name: playwright
    command: npx -y playwright@1.49.1 run-server --port 3000 --host 0.0.0.0

  open-webui:
    environment:
      - 'RAG_WEB_LOADER_ENGINE=playwright'
      - 'PLAYWRIGHT_WS_URI=ws://playwright:3000'