FROM python:3.10.12

WORKDIR /backend

# Install PostgreSQL client and other dependencies
RUN apt-get update && apt-get install -y postgresql-client

# Upgrade pip
RUN pip install --upgrade pip

# Copy project files to the container
COPY . .

# Install project dependencies including debugpy
RUN pip3 install -r requirements.txt

# Make scripts executable
RUN chmod +x ./wait-for-postgres.sh
RUN chmod +x ./django-entrypoint-dev.sh