export const AI_AGENT_PROFILE_INIT = "AGENT_INIT";

export const GET_AI_AGENT_PROFILE = "GET_AI_AGENT_PROFILE";
export const GET_AI_AGENT_PROFILE_INIT_STATE = "GET_AI_AGENT_PROFILE_INIT_STATE";
export const GET_AI_AGENT_PROFILE_SUCCESS = "GET_AI_AGENT_PROFILE_SUCCESS";
export const GET_AI_AGENT_PROFILE_FAILED = "GET_AI_AGENT_PROFILE_FAILED";

export const UPDATE_AI_AGENT_PROFILE_DATA = "UPDATE_AI_AGENT_PROFILE_DATA";
export const UPDATE_AI_AGENT_PROFILE_DATA_INIT_STATE = "UPDATE_AI_AGENT_PROFILE_DATA_INIT_STATE"; 
export const UPDATE_AI_AGENT_PROFILE_DATA_SUCCESS = "UPDATE_AI_AGENT_PROFILE_DATA_SUCCESS";
export const UPDATE_AI_AGENT_PROFILE_DATA_FAILED = "UPDATE_AI_AGENT_PROFILE_DATA_FAILED";

export const UPDATE_AI_AGENT_PROFILE_AVATAR = "UPDATE_AI_AGENT_PROFILE_AVATAR";
export const UPDATE_AI_AGENT_PROFILE_AVATAR_INIT_STATE = "UPDATE_AI_AGENT_PROFILE_AVATAR_INIT_STATE";
export const UPDATE_AI_AGENT_PROFILE_AVATAR_SUCCESS = "UPDATE_AI_AGENT_PROFILE_AVATAR_SUCCESS";
export const UPDATE_AI_AGENT_PROFILE_AVATAR_FAILED = "UPDATE_AI_AGENT_PROFILE_AVATAR_FAILED";