# Generated by Django 4.2.1 on 2024-02-15 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 2, 16, 20, 10, 28, 991567, tzinfo=datetime.timezone.utc))),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Email Confirm Token',
                'verbose_name_plural': 'Email Confirm Tokens',
            },
        ),
    ]
