# Generated by Django 4.2.1 on 2024-02-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationtoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
