# Generated by Django 4.2.1 on 2023-09-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_models_app', '0001_initial'),
        ('agent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='nlp_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nlp_models', to='nlp_models_app.nlpmodel'),
        ),
    ]
