# Generated by Django 4.2.1 on 2024-01-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0002_alter_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
