# Generated by Django 4.2.1 on 2023-09-28 12:55

from django.db import migrations, models
import django.db.models.deletion
import nlp_models_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NlpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_token', models.DecimalField(decimal_places=5, max_digits=10)),
                ('description', models.TextField(max_length=2000)),
                ('avatar', models.ImageField(blank=True, upload_to=nlp_models_app.models.get_image_filename)),
                ('nlp_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlp_models_app.nlpmodel')),
            ],
        ),
    ]
