export const CHAT_INIT = "CHAT_INIT";

export const FETCH_CHATS = "FETCH_CHATS";
export const FETCH_CHATS_INIT_STATE = "FETCH_CHATS_INIT_STATE"
export const FETCH_CHATS_SUCCESS = "FETCH_CHATS_SUCCESS";
export const FETCH_CHATS_FAILED = "FETCH_CHATS_FAILED";

export const ADD_CHAT = "ADD_CHAT";
export const ADD_CHAT_INIT_STATE = "ADD_CHAT_INIT_STATE";
export const ADD_CHAT_SUCCESS = "ADD_CHAT_SUCCESS";
export const ADD_CHAT_FAILED = "ADD_CHAT_FAILED";

export const DELETE_CHAT = "DELETE_CHAT";
export const DELETE_CHAT_INIT_STATE = "DELETE_CHAT_INIT_STATE";
export const DELETE_CHAT_SUCCESS = "DELETE_CHAT_SUCCESS";
export const DELETE_CHAT_FAILED = "DELETE_CHAT_FAILED";
    
export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT";
export const SET_ACTIVE_CHAT_INIT_STATE = "SET_ACTIVE_CHAT_INIT_STATE";
export const SET_ACTIVE_CHAT_SUCCESS = "SET_ACTIVE_CHAT_SUCCESS";
export const SET_ACTIVE_CHAT_FAILED = "SET_ACTIVE_CHAT_FAILED";