export const FETCH_CHATS = "FETCH_CHATS";
export const FETCH_CHATS_INIT_STATE = "FETCH_CHATS_INIT_STATE"
export const FETCH_CHATS_SUCCESS = "FETCH_CHATS_SUCCESS";
export const FETCH_CHATS_FAILED = "FETCH_CHATS_FAILED";

export const ADD_CHAT = "ADD_CHAT";
export const ADD_CHAT_INIT_STATE = "ADD_CHAT_INIT_STATE";
export const ADD_CHAT_SUCCESS = "ADD_CHAT_SUCCESS";
export const ADD_CHAT_FAILED = "ADD_CHAT_FAILED";

export const DELETE_CHAT = "DELETE_CHAT";
export const DELETE_CHAT_INIT_STATE = "DELETE_CHAT_INIT_STATE";
export const DELETE_CHAT_SUCCESS = "DELETE_CHAT_SUCCESS";
export const DELETE_CHAT_FAILED = "DELETE_CHAT_FAILED";
    
export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const FETCH_MESSAGES_INIT_STATE = "FETCH_MESSAGES_INIT_STATE";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILED = "FETCH_MESSAGES_FAILED";
    
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_MESSAGE_INIT_STATE = "DELETE_MESSAGE_INIT_STATE";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAILED = "DELETE_MESSAGE_FAILED";

export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT";
export const SHOW_CHAT_WINDOW = "SHOW_CHAT_WINDOW";
export const SET_ACTIVE_NEW_CHAT = "SET_ACTIVE_NEW_CHAT";

export const WS_CONNECTION_START = 'WS_CONNECTION_START';
export const WS_CONNECTION_KILL = 'WS_CONNECTION_KILL';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_RECEIVE_MESSAGE_CHUNK = 'WS_RECEIVE_MESSAGE_CHUNK';
