# Generated by Django 4.2.1 on 2023-07-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='addressee',
            new_name='addressee_id',
        ),
    ]
