# Generated by Django 4.2.1 on 2023-07-24 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0003_alter_message_answer_text_alter_message_message_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dialog',
            new_name='Chat',
        ),
    ]
