# Generated by Django 4.2.1 on 2023-08-18 11:34
import random, string
from django.contrib.auth import get_user_model
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('user_app', '0003_rename_profile_agent'),
        ('chat_app', '0003_alter_message_answer_text_alter_message_message_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dialog',
            new_name='Chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='owner_id',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='owner_id',
                                    to='user_app.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='addressee_id',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='addressee_id', to='user_app.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='owner_id',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='user_app.agent'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='dialog_id',
            new_name='chat_id'
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='message',
            name='answer_text',
        ),
    ]
