# Generated by Django 4.2.1 on 2024-02-22 12:47

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_transfer_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='addressee_id',
            new_name='addressee_agent',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='owner_id',
            new_name='owner_agent',
        ),
        # The DeleteModel operation for 'Message' remains as it was, assuming it's intentionally part of this migration.
        migrations.DeleteModel(
            name='Message',
        ),
    ]