# Generated by Django 4.2.1 on 2023-09-23 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_profile_agent'),
        ('chat_app', '0005_message_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='addressee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressee', to='user_app.agent'),
        ),
    ]
