# Generated by Django 4.2.1 on 2023-09-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('agent_app', '0001_initial'),
        ('chat_app', '0007_add_Gpts_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='addressee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressee_id',
                                    to='agent_app.agent'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id',
                                    to='agent_app.agent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='addressee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='addressee', to='agent_app.agent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_app.agent'),
        ),
    ]
