# Generated by Django 4.2.1 on 2023-12-06 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0002_alter_agent_id'),
        ('chat_app', '0010_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='addressee_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='owner_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_agent', to='agent_app.agent'),
        ),
    ]
