# Generated by Django 4.2.1 on 2024-01-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0002_alter_agent_id'),
        ('chat_app', '0011_remove_chat_addressee_id_remove_chat_owner_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='addressee_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressee_agent', to='agent_app.agent'),
        ),
    ]
