# Generated by Django 4.2.1 on 2024-01-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0002_alter_agent_id'),
        ('chat_app', '0008_alter_chat_addressee_id_alter_chat_owner_id_and_more'),
        ('chat_app', '0012_chat_addressee_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='addressee_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressee_agent_chats', to='agent_app.agent'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='owner_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_agent_chats', to='agent_app.agent'),
        ),
    ]
