export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";

export const AUTH_FAILED = "AUTH_API_FAILED";

export const CONFIRM_EMAIL = 'CONFIRM_EMAIL';
export const CONFIRM_EMAIL_SUCCESS = 'CONFIRM_EMAIL_SUCCESS';

export const SEND_CONFIRMATION_EMAIL = 'SEND_CONFIRMATION_EMAIL';
export const SEND_CONFIRMATION_EMAIL_SUCCESS = 'SEND_CONFIRMATION_EMAIL_SUCCESS';

export const RESET_PASSWORD_CONFIRM = "RESET_PASSWORD_CONFIRM";
export const RESET_PASSWORD_CONFIRM_SUCCESS = "RESET_PASSWORD_CONFIRM_SUCCESS";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const HIDE_CHANGE_PASSWORD_SUCCESS_MESSAGE = "HIDE_CHANGE_PASSWORD_SUCCESS_MESSAGE";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";


export const VALIDATE_RESET_TOKEN = "VALIDATE_RESET_TOKEN";
export const VALIDATE_RESET_TOKEN_SUCCESS = "VALIDATE_RESET_TOKEN_SUCCESS";

export const REFRESH_TOKEN_UPDATE = "REFRESH_TOKEN_UPDATE";
export const REFRESH_TOKEN_UPDATE_SUCCESS = "REFRESH_TOKEN_UPDATE_SUCCESS";
export const REFRESH_TOKEN_UPDATE_FAILURE = "REFRESH_TOKEN_UPDATE_FAILURE";

export const ADD_AUTHENTICATED_API_REQUEST = "ADD_AUTHENTICATED_API_REQUEST";
export const CLEAR_AUTHENTICATED_API_REQUESTS_QUEUE = "CLEAR_AUTHENTICATED_API_REQUESTS_QUEUE";
export const ADD_WEB_SOCKET_REQUEST = "ADD_WEB_SOCKET_REQUEST";
export const CLEAR_WEB_SOCKET_REQUESTS_QUEUE = "CLEAR_WEB_SOCKET_REQUESTS_QUEUE";