export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_INIT_STATE = "LOGIN_USER_INIT_STATE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_INIT_STATE = "LOGOUT_USER_INIT_STATE";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_INIT_STATE = "REGISTER_USER_INIT_STATE";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const SEND_CONFIRMATION_EMAIL = "SEND_CONFIRMATION_EMAIL";
export const SEND_CONFIRMATION_EMAIL_INIT_STATE = "SEND_CONFIRMATION_EMAIL_INIT_STATE";
export const SEND_CONFIRMATION_EMAIL_SUCCESS = "SEND_CONFIRMATION_EMAIL_SUCCESS";
export const SEND_CONFIRMATION_EMAIL_FAILURE = "SEND_CONFIRMATION_EMAIL_FAILURE";

export const CONFIRM_EMAIL = "CONFIRM_EMAIL";
export const CONFIRM_EMAIL_INIT_STATE = "CONFIRM_EMAIL_INIT_STATE";
export const CONFIRM_EMAIL_SUCCESS = "CONFIRM_EMAIL_SUCCESS";
export const CONFIRM_EMAIL_FAILURE = "CONFIRM_EMAIL_FAILURE";

export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_INIT_STATE = "FORGET_PASSWORD_INIT_STATE";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAILURE = "FORGET_PASSWORD_FAILURE";

export const VALIDATE_PASSWORD_RESET_TOKEN = "VALIDATE_PASSWORD_RESET_TOKEN";
export const VALIDATE_PASSWORD_RESET_TOKEN_INIT_STATE = "VALIDATE_PASSWORD_RESET_TOKEN_INIT_STATE";
export const VALIDATE_PASSWORD_RESET_TOKEN_SUCCESS = "VALIDATE_PASSWORD_RESET_TOKEN_SUCCESS";
export const VALIDATE_PASSWORD_RESET_TOKEN_FAILURE = "VALIDATE_PASSWORD_RESET_TOKEN_FAILURE";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_INIT_STATE = "RESET_PASSWORD_INIT_STATE";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_INIT_STATE = "CHANGE_PASSWORD_INIT_STATE";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const HIDE_CHANGE_PASSWORD_SUCCESS_MESSAGE = "HIDE_CHANGE_PASSWORD_SUCCESS_MESSAGE";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

export const REFRESH_TOKEN_UPDATE = "REFRESH_TOKEN_UPDATE";
export const REFRESH_TOKEN_UPDATE_INIT_STATE = "REFRESH_TOKEN_UPDATE_INIT_STATE";
export const REFRESH_TOKEN_UPDATE_SUCCESS = "REFRESH_TOKEN_UPDATE_SUCCESS";
export const REFRESH_TOKEN_UPDATE_FAILURE = "REFRESH_TOKEN_UPDATE_FAILURE";

export const ADD_AUTHENTICATED_API_REQUEST = "ADD_AUTHENTICATED_API_REQUEST";
export const CLEAR_AUTHENTICATED_API_REQUESTS_QUEUE = "CLEAR_AUTHENTICATED_API_REQUESTS_QUEUE";
export const ADD_WEB_SOCKET_REQUEST = "ADD_WEB_SOCKET_REQUEST";
export const CLEAR_WEB_SOCKET_REQUESTS_QUEUE = "CLEAR_WEB_SOCKET_REQUESTS_QUEUE";