export const ADD_WEB_SOCKET_REQUEST = "ADD_WEB_SOCKET_REQUEST";
export const CLEAR_WEB_SOCKET_REQUESTS_QUEUE = "CLEAR_WEB_SOCKET_REQUESTS_QUEUE";

export const WS_CONNECTION = 'WS_CONNECTION';
export const WS_CONNECTION_KILL = 'WS_CONNECTION_KILL';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_FAILED = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';