export const ADD_WEB_SOCKET_REQUEST = "ADD_WEB_SOCKET_REQUEST";
export const CLEAR_WEB_SOCKET_REQUESTS_QUEUE = "CLEAR_WEB_SOCKET_REQUESTS_QUEUE";

export const WS_CONNECTION = 'WS_CONNECTION';
export const WS_CONNECTION_KILL = 'WS_CONNECTION_KILL';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_FAILED = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';

export const WS_SEND = "WS_SEND";
export const WS_SEND_INIT_STATE = "WS_SEND_INIT_STATE";
export const WS_SEND_SUCCESS = "WS_SEND_SUCCESS";
export const WS_SEND_FAILED = "WS_SEND_FAILED";

export const WS_RECEIVE_MESSAGE = 'WS_RECEIVE_MESSAGE';