# Generated by Django 4.2.1 on 2023-11-15 19:49

from agent_app.models import Agent
from django.db import migrations, models
import django.db.models.deletion
import user_agent_profiles_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_app', 'Agent'),
        ('agent_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgentProfiles',
            fields=[
                ('avatar', models.ImageField(blank=True, upload_to=user_agent_profiles_app.models.get_image_filename)),
                ('first_name', models.TextField(max_length=32)),
                ('last_name', models.TextField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=Agent, primary_key=True)),
            ],
        ),
    ]
