# Generated by Django 4.2.1 on 2023-12-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0002_message_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='addressee_agent_id',
            new_name='addressee_agent',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='owner_agent_id',
            new_name='owner_agent',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='request_id',
            new_name='request',
        ),
    ]
