# Generated by Django 4.2.1 on 2024-01-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0002_alter_agent_id'),
        ('message_app', '0003_rename_addressee_agent_id_message_addressee_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='addressee_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresse_agent_messages', to='agent_app.agent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_messages', to='message_app.message'),
        ),
    ]
