# Generated by Django 4.2.1 on 2024-02-22 10:34

from django.db import migrations

def transfer_agents(apps, schema_editor):
    OldAgent = apps.get_model('user_app', 'Agent')
    NewAgent = apps.get_model('agent_app', 'Agent')
    AiAgentProfile = apps.get_model('user_agent_profile_app', 'AiAgentProfile')
    
    for old_agent in OldAgent.objects.all():
        new_agent = NewAgent.objects.create(
            user_id = old_agent.user_id,
            name = old_agent.first_name + " " + old_agent.last_name
        )

        AiAgentProfile.objects.create(
            user_agent = new_agent,
            avatar = old_agent.avatar ,
            first_name = old_agent.first_name ,
            last_name = old_agent.last_name,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0001_initial'),
        ('user_app', '0001_initial'),
        ('user_agent_profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_agents),
    ]