# Generated by Django 4.2.1 on 2023-08-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Agent',
        ),
    ]
