# Generated by Django 4.2.1 on 2024-02-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_alter_chat_addressee_agent_alter_chat_owner_agent'),
        ('user_app', '0002_transfer_agent_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
