# Generated by Django 4.2.1 on 2023-09-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_profile_agent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='ProfileUser',
        ),
    ]
