# Generated by Django 4.2.1 on 2023-11-09 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_rename_agent_profileuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
