# Generated by Django 4.2.1 on 2023-11-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_profileuser_created_at_profileuser_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
