export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

export const UPDATE_PROFILE_DATA = "UPDATE_PROFILE_DATA";
export const UPDATE_PROFILE_DATA_SUCCESS = "UPDATE_PROFILE_DATA_SUCCESS";
export const HIDE_PROFILE_DATA_SUCCESS_MESSAGE = "HIDE_PROFILE_DATA_SUCCESS_MESSAGE";
export const UPDATE_PROFILE_DATA_FAILED = "UPDATE_PROFILE_DATA_FAILED";

export const UPDATE_PROFILE_AVATAR = "UPDATE_PROFILE_AVATAR";
export const UPDATE_PROFILE_AVATAR_SUCCESS = "UPDATE_PROFILE_AVATAR_SUCCESS";
export const HIDE_PROFILE_AVATAR_SUCCESS_MESSAGE = "HIDE_PROFILE_AVATAR_SUCCESS_MESSAGE";
export const UPDATE_PROFILE_AVATAR_FAILED = "UPDATE_PROFILE_AVATAR_FAILED";