export const GET_AUTHORIZED_USER = "GET_AUTHORIZED_USER";
export const GET_AUTHORIZED_USER_SUCCESS = "GET_AUTHORIZED_USER_SUCCESS";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const DELETE_USER = "DELETE_USER";

export const USER_FAILED = "USER_API_FAILED";


